# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_gc_common.proto',
  package='edu.tigers.sumatra.referee.proto',
  syntax='proto2',
  serialized_options=_b('Z=github.com/RoboCup-SSL/ssl-game-controller/internal/app/state'),
  serialized_pb=_b('\n\x13ssl_gc_common.proto\x12 edu.tigers.sumatra.referee.proto\"K\n\x07RobotId\x12\n\n\x02id\x18\x01 \x01(\r\x12\x34\n\x04team\x18\x02 \x01(\x0e\x32&.edu.tigers.sumatra.referee.proto.Team*)\n\x04Team\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\x08\n\x04\x42LUE\x10\x02*1\n\x08\x44ivision\x12\x0f\n\x0b\x44IV_UNKNOWN\x10\x00\x12\t\n\x05\x44IV_A\x10\x01\x12\t\n\x05\x44IV_B\x10\x02\x42?Z=github.com/RoboCup-SSL/ssl-game-controller/internal/app/state')
)

_TEAM = _descriptor.EnumDescriptor(
  name='Team',
  full_name='edu.tigers.sumatra.referee.proto.Team',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=134,
  serialized_end=175,
)
_sym_db.RegisterEnumDescriptor(_TEAM)

Team = enum_type_wrapper.EnumTypeWrapper(_TEAM)
_DIVISION = _descriptor.EnumDescriptor(
  name='Division',
  full_name='edu.tigers.sumatra.referee.proto.Division',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIV_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIV_A', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIV_B', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=177,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_DIVISION)

Division = enum_type_wrapper.EnumTypeWrapper(_DIVISION)
UNKNOWN = 0
YELLOW = 1
BLUE = 2
DIV_UNKNOWN = 0
DIV_A = 1
DIV_B = 2



_ROBOTID = _descriptor.Descriptor(
  name='RobotId',
  full_name='edu.tigers.sumatra.referee.proto.RobotId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='edu.tigers.sumatra.referee.proto.RobotId.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='edu.tigers.sumatra.referee.proto.RobotId.team', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=132,
)

_ROBOTID.fields_by_name['team'].enum_type = _TEAM
DESCRIPTOR.message_types_by_name['RobotId'] = _ROBOTID
DESCRIPTOR.enum_types_by_name['Team'] = _TEAM
DESCRIPTOR.enum_types_by_name['Division'] = _DIVISION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotId = _reflection.GeneratedProtocolMessageType('RobotId', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTID,
  __module__ = 'ssl_gc_common_pb2'
  # @@protoc_insertion_point(class_scope:edu.tigers.sumatra.referee.proto.RobotId)
  ))
_sym_db.RegisterMessage(RobotId)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
